name: checkout
on: [push]

jobs: 
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - uses: actions/checkout@v3
      - name: List files After
        run: ls -a 
