name: docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: node:20.3-alpine3.17

            env:
                API_URL: some-url.com
            
            ports:
                - 80
        steps:
            - name: Log node & OS Versions
              run: |
                node -v
                cat /etc/os-release

            - name: Container in a step
              uses: docker://node18.16-alpine3.17
              with:
                entrypoint: /usr/local/bin/node
                args: -p 2+3

            - name: Container in a step
              uses: docker://node18.16-alpine3.17
              with:
                args: -v

